Repository kubevirt/kubevirt.core, pull requests merged in 2023-09, with the labels that each got.

#23 Flatten groups and allow to control creation of additional groups
  changelogs/fragments/0_flatten_groups.yml
  changelogs/fragments/1_add_create_groups.yml
  plugins/inventory/kubevirt.py
  tests/integration/targets/inventory_kubevirt/test.kubevirt.yml
  tests/integration/targets/inventory_kubevirt/test.label.kubevirt.yml
  tests/integration/targets/inventory_kubevirt/test.net.kubevirt.yml
Labels: approved, release-note, size/M, lgtm, dco-signoff: yes

#24 kubevirt_vm_info: Add info module for VirtualMachines
  .github/workflows/ci.yml
  changelogs/fragments/3_add_kubevirt_vm_info.yml
  examples/play-info-list.yml
  examples/play-info.yml
  hack/e2e-setup.sh
  plugins/modules/kubevirt_vm_info.py
  tests/integration/targets/kubevirt_vm_info/playbook.yml
  tests/integration/targets/kubevirt_vm_info/runme.sh
  tests/unit/modules/test_module_kubevirt_vm_info.py
Labels: size/L, approved, release-note, lgtm, dco-signoff: yes

#26 Bump version to 1.1.0
  galaxy.yml
Labels: release-note-none, size/XS, dco-signoff: yes

#27 Drop old changelog fragments
  changelogs/fragments/0_flatten_groups.yml
  changelogs/fragments/1_add_create_groups.yml
  changelogs/fragments/3_add_kubevirt_vm_info.yml
Labels: release-note-none, size/XS, dco-signoff: yes

#28 changelog.yaml: Fix indentation for linter
  changelogs/changelog.yaml
Labels: release-note-none, size/S, dco-signoff: yes

#29 Add changelog to lint ignores
  .ansible-lint
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes
