Repository kubevirt/kubevirt.core, pull requests merged in 2023-08, with the labels that each got.

#8 Rename collection to kubevirt.core
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  README.md
  docs/index.rst
  examples/inventory.kubevirt.yml
  examples/kubesecondarydns.kubevirt.yml
  examples/play-create-dv.yml
  examples/play-create-min.yml
  examples/play-create.yml
  examples/play-delete-dv.yml
  examples/play-delete.yml
  examples/services.kubevirt.yml
  galaxy.yml
  plugins/inventory/kubevirt.py
  plugins/modules/kubevirt_vm.py
  tests/integration/targets/inventory_kubevirt/runme.sh
  tests/unit/modules/test_module_kubevirt_vm.py
Labels: approved, size/M, lgtm, dco-signoff: yes

#9 Bump to 0.1.1
  .ansible-lint
  .github/workflows/ci.yml
  galaxy.yml
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#10 Prerelease
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/release.yml
  MAINTAINING.md
  README.md
  REVIEW_CHECKLIST.md
  docs/testing.md
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes

#11 Meta runtime fix
  changelogs/changelog.yaml
  meta/runtime.yml
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#12 release: Run other workflows explicitly
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes

#14 Bump version to 1.0.0
  changelogs/changelog.yaml
  galaxy.yml
Labels: approved, release-note, lgtm, size/S, dco-signoff: yes

#16 ci: Exclude py3.9 with Ansible milestone
  .github/workflows/ci.yml
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#20 README.md: Drop note about supported collection for now
  README.md
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#21 install galaxy ansible.posix, not from sources
  .github/workflows/ci.yml
  .github/workflows/integration.yml
Labels: release-note-none, approved, size/M, lgtm, dco-signoff: yes
