Repository kubevirt/kubevirt.core, pull requests merged in 2024-08, with the labels that each got.

#127 e2e-setup: Use virt-operator to deploy common-instancetypes
  hack/e2e-setup.sh
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#131 cleanup(yamllint): Add yamllint options required by ansible-lint
  .yamllint
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#130 Run integration tests in random namespaces
  .gitignore
  tests/integration/targets/inventory_kubevirt/cleanup.yml.j2
  tests/integration/targets/inventory_kubevirt/generate.yml
  tests/integration/targets/inventory_kubevirt/playbook.yml.j2
  tests/integration/targets/inventory_kubevirt/runme.sh
  tests/integration/targets/inventory_kubevirt/test.cache.kubevirt.yml.j2
  tests/integration/targets/inventory_kubevirt/test.kubevirt.yml.j2
  tests/integration/targets/inventory_kubevirt/test.label.kubevirt.yml.j2
  tests/integration/targets/inventory_kubevirt/test.net.kubevirt.yml.j2
  tests/integration/targets/inventory_kubevirt/verify.yml.j2
  tests/integration/targets/kubevirt_vm/generate.yml
  tests/integration/targets/kubevirt_vm/playbook.yml.j2
  tests/integration/targets/kubevirt_vm/runme.sh
  tests/integration/targets/kubevirt_vm/test.kubevirt.yml.j2
  tests/integration/targets/kubevirt_vm/verify.yml.j2
  tests/integration/targets/kubevirt_vm/wait_for_vm.yml.j2
  tests/integration/targets/kubevirt_vm_info/generate.yml
  tests/integration/targets/kubevirt_vm_info/playbook.yml.j2
  tests/integration/targets/kubevirt_vm_info/runme.sh
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, minor_changes

#132 Source extra_env.sh file if exists in integration tests
  tests/integration/targets/inventory_kubevirt/runme.sh
  tests/integration/targets/kubevirt_vm/runme.sh
  tests/integration/targets/kubevirt_vm_info/runme.sh
  tests/integration/targets/kubevirt_vmi_info/runme.sh
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes

#128 chore(renovate): Add renovate config
  renovate.json
Labels: release-note-none, approved, size/M, lgtm, dco-signoff: yes

#133 renovate: Enable dashboard and format config
  renovate.json
Labels: release-note-none, approved, size/M, lgtm, dco-signoff: yes
