Repository kubevirt/kubevirt.core, pull requests merged in 2024-05, with the labels that each got.

#96 Add inventory unit tests
  plugins/inventory/kubevirt.py
  tests/unit/plugins/inventory/test_kubevirt.py
Labels: release-note-none, size/XL, approved, lgtm, dco-signoff: yes

#95 Provide links for docsite and improve docs by adding markup
  docs/docsite/links.yml
  plugins/inventory/kubevirt.py
  plugins/modules/kubevirt_vm.py
  plugins/modules/kubevirt_vm_info.py
Labels: documentation, size/L, approved, lgtm, dco-signoff: yes, minor_changes

#100 fix: Ensure compatibility with kubernetes.core >=3.10,<4.1.0
  README.md
  galaxy.yml
  plugins/inventory/kubevirt.py
  requirements.yml
Labels: approved, release-note, lgtm, size/S, dco-signoff: yes, bugfixes, minor_changes

#102 chore: Bump version to 1.4.0
  changelogs/changelog.yaml
  galaxy.yml
Labels: approved, release-note, lgtm, size/XS, dco-signoff: yes
