Repository kubevirt/kubevirt.core, pull requests merged in 2024-04, with the labels that each got.

#70 fix: Explicity set ansible_port
  plugins/inventory/kubevirt.py
Labels: approved, release-note, lgtm, size/XS, dco-signoff: yes, minor_changes

#71 chore: Update CHANGELOG.rst
  CHANGELOG.rst
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#73 fix: Return early to avoid adding empty groups.
  plugins/inventory/kubevirt.py
Labels: approved, release-note, lgtm, size/XS, dco-signoff: yes, bugfixes

#74 tests: Add --create-registry to hack/e2e-setup.sh
  hack/e2e-setup.sh
Labels: release-note-none, approved, size/M, lgtm, dco-signoff: yes

#77 fix: add composite vars to inventory
  plugins/inventory/kubevirt.py
Labels: approved, release-note, lgtm, size/S, dco-signoff: yes

#78 Add helper to build virtualenv and vscode configuration
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  Makefile
  galaxy.yml
  test-requirements.txt
  tests/requirements.txt
  tests/unit/requirements.txt
  tox-ansible.ini
  tox.ini
Labels: release-note-none, approved, size/M, lgtm, dco-signoff: yes

#79 Migrate existing unit tests to pytest and add basic unit tests for inventory plugin
  test-requirements.txt
  tests/unit/conftest.py
  tests/unit/modules/test_module_kubevirt_vm.py
  tests/unit/modules/test_module_kubevirt_vm_info.py
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/plugins/modules/test_kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm_info.py
  tests/unit/utils/ansible_module_mock.py
Labels: release-note-none, size/XL, approved, lgtm, dco-signoff: yes

#75 feat: Set ansible_connection to winrm for Windows hosts
  plugins/inventory/kubevirt.py
  test-requirements.txt
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/utils/ansible_module_mock.py
  tests/unit/utils/merge_dicts.py
Labels: size/L, approved, release-note, lgtm, dco-signoff: yes, bugfixes

#80 chore: Add requirements.txt for ansible-test units
  tests/requirements.txt
  tests/unit/requirements.txt
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes

#81 chore: Bump version to 1.3.0
  galaxy.yml
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#82 chore: Update testing instructions
  docs/developing.md
  docs/testing.md
  galaxy.yml
  test-requirements.txt
Labels: documentation, size/L, release-note-none, approved, lgtm, dco-signoff: yes

#83 chore: Bump version to 1.3.1
  galaxy.yml
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#84 chore: Bump version to 1.3.2
  changelogs/changelog.yaml
  galaxy.yml
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#88 cleanup: Cleanup YAML passed to k8s module
  plugins/modules/kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm.py
Labels: size/L, approved, lgtm, dco-signoff: yes, minor_changes

#89 fix(kubevirt_vm): Set wait_condition based on running
  plugins/modules/kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm.py
Labels: approved, release-note, size/M, lgtm, dco-signoff: yes, bugfixes, minor_changes

#91 feat(kubevirt_vm_info): Set wait_condition based on running
  plugins/modules/kubevirt_vm_info.py
  tests/unit/plugins/modules/test_kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm_info.py
Labels: approved, size/M, lgtm, dco-signoff: yes, minor_changes

#92 tests: add render_template unit tests
  tests/unit/plugins/modules/test_kubevirt_vm.py
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes
