Repository kubevirt/kubevirt.core, pull requests merged in 2024-07, with the labels that each got.

#115 Several minor improvements
  .github/workflows/ci.yml
  .github/workflows/integration.yml
  .gitignore
  .vscode/launch.json
  .vscode/module_args/kubevirt_vm.json
  .vscode/module_args/kubevirt_vm_info.json
  Makefile
  galaxy.yml
  tests/unit/plugins/modules/test_kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm_info.py
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, minor_changes

#116 Add documentation running coverage analysis.
  docs/testing.md
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes

#118 cleanup(kubevirt_vm): Drop dependency on Jinja2
  README.md
  plugins/modules/kubevirt_vm.py
  requirements.txt
  tests/unit/plugins/modules/test_kubevirt_vm.py
  tests/unit/requirements.txt
Labels: size/L, approved, release-note, lgtm, dco-signoff: yes

#114 feat,test(inventory): Support listing stopped VMs and major rework of unit tests
  examples/default.kubevirt.yml
  examples/play-create-stopped.yml
  plugins/inventory/kubevirt.py
  tests/integration/targets/inventory_kubevirt/cleanup.yml
  tests/integration/targets/inventory_kubevirt/playbook.yml
  tests/integration/targets/inventory_kubevirt/verify.yml
  tests/unit/plugins/inventory/blackbox/test_kubevirt_ansible_connection_winrm.py
  tests/unit/plugins/inventory/blackbox/test_kubevirt_set_composable_vars.py
  tests/unit/plugins/inventory/blackbox/test_kubevirt_stopped_vm.py
  tests/unit/plugins/inventory/conftest.py
  tests/unit/plugins/inventory/constants.py
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/plugins/inventory/test_kubevirt_add_host.py
  tests/unit/plugins/inventory/test_kubevirt_composable_vars.py
  tests/unit/plugins/inventory/test_kubevirt_fetch_objects.py
  tests/unit/plugins/inventory/test_kubevirt_format_dynamic_api_exc.py
  tests/unit/plugins/inventory/test_kubevirt_get_resources.py
  tests/unit/plugins/inventory/test_kubevirt_get_ssh_services_for_namespace.py
  tests/unit/plugins/inventory/test_kubevirt_inventory_options.py
  tests/unit/plugins/inventory/test_kubevirt_populate_inventory_from_namespace.py
  tests/unit/plugins/inventory/test_kubevirt_set_ansible_host_and_port.py
  tests/unit/plugins/inventory/test_kubevirt_set_common_vars.py
  tests/unit/plugins/inventory/test_kubevirt_set_vars_from_vmi.py
  tests/unit/plugins/inventory/test_kubevirt_setup.py
  tests/unit/plugins/inventory/test_kubevirt_verify_file.py
Labels: approved, release-note, size/XXL, lgtm, dco-signoff: yes, major_changes

#117 cleanup(inventory): Drop support for multiple connections
  .yamllint
  examples/inventory.kubevirt.yml
  examples/kubesecondarydns.kubevirt.yml
  examples/services.kubevirt.yml
  plugins/doc_fragments/kubevirt_auth_options.py
  plugins/inventory/kubevirt.py
  tests/integration/targets/inventory_kubevirt/test.kubevirt.yml
  tests/integration/targets/inventory_kubevirt/test.label.kubevirt.yml
  tests/integration/targets/inventory_kubevirt/test.net.kubevirt.yml
  tests/integration/targets/kubevirt_vm/test.kubevirt.yml
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/plugins/inventory/test_kubevirt_connections_compatibility.py
  tests/unit/plugins/inventory/test_kubevirt_fetch_objects.py
  tests/unit/plugins/inventory/test_kubevirt_parse.py
Labels: size/XL, approved, release-note, lgtm, dco-signoff: yes, breaking_changes

#121 chore(OWNERS): make jcanocan an approver
  OWNERS
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#119 fix(inventory): Fix inventory source caching
  .gitignore
  examples/cache.kubevirt.yml
  plugins/inventory/kubevirt.py
  test-requirements.txt
  tests/integration/targets/inventory_kubevirt/runme.sh
  tests/integration/targets/inventory_kubevirt/test.cache.kubevirt.yml
  tests/integration/targets/inventory_kubevirt/verify.yml
  tests/unit/plugins/inventory/blackbox/test_kubevirt_ansible_connection_winrm.py
  tests/unit/plugins/inventory/blackbox/test_kubevirt_set_composable_vars.py
  tests/unit/plugins/inventory/blackbox/test_kubevirt_stopped_vm.py
  tests/unit/plugins/inventory/conftest.py
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/plugins/inventory/test_kubevirt_add_host.py
  tests/unit/plugins/inventory/test_kubevirt_fetch_objects.py
  tests/unit/plugins/inventory/test_kubevirt_parse.py
  tests/unit/plugins/inventory/test_kubevirt_populate_inventory_from_namespace.py
  tests/unit/plugins/inventory/test_kubevirt_set_ansible_host_and_port.py
  tests/unit/plugins/inventory/test_kubevirt_set_common_vars.py
  tests/unit/plugins/inventory/test_kubevirt_set_vars_from_vmi.py
  tests/unit/requirements.txt
Labels: approved, release-note, size/XXL, lgtm, dco-signoff: yes, bugfixes, minor_changes

#122 Several small cleanups
  README.md
  plugins/inventory/kubevirt.py
  tests/unit/plugins/inventory/blackbox/test_kubevirt_ansible_connection_winrm.py
  tests/unit/plugins/inventory/blackbox/test_kubevirt_set_composable_vars.py
  tests/unit/plugins/inventory/blackbox/test_kubevirt_stopped_vm.py
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/plugins/inventory/test_kubevirt_add_host.py
  tests/unit/plugins/inventory/test_kubevirt_connections_compatibility.py
  tests/unit/plugins/inventory/test_kubevirt_fetch_objects.py
  tests/unit/plugins/inventory/test_kubevirt_format_dynamic_api_exc.py
  tests/unit/plugins/inventory/test_kubevirt_get_resources.py
  tests/unit/plugins/inventory/test_kubevirt_get_ssh_services_for_namespace.py
  tests/unit/plugins/inventory/test_kubevirt_parse.py
  tests/unit/plugins/inventory/test_kubevirt_populate_inventory_from_namespace.py
  tests/unit/plugins/inventory/test_kubevirt_set_ansible_host_and_port.py
  tests/unit/plugins/inventory/test_kubevirt_set_common_vars.py
  tests/unit/plugins/inventory/test_kubevirt_set_vars_from_vmi.py
  tests/unit/plugins/modules/test_kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm_info.py
Labels: release-note-none, approved, size/XXL, lgtm, dco-signoff: yes, minor_changes

#124 feat(kubevirt_vm): Add support for RunStrategy
  examples/play-create-run-strategy.yml
  plugins/modules/kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm.py
Labels: size/L, approved, lgtm, dco-signoff: yes, minor_changes

#125 chore: Bump version to 2.0.0
  changelogs/changelog.yaml
  galaxy.yml
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes, breaking_changes
