Repository kubevirt/kubevirt.core, pull requests merged in 2024-06, with the labels that each got.

#104 Bump tested ansible-core versions to 2.15-2.17
  .github/workflows/ci.yml
  .github/workflows/integration.yml
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes

#103 Make kubevirt_vm tests more robust
  tests/integration/targets/kubevirt_vm/runme.sh
  tests/integration/targets/kubevirt_vm/verify.yml
  tests/integration/targets/kubevirt_vm/wait_for_vm.yml
Labels: release-note-none, approved, size/M, lgtm, dco-signoff: yes

#105 chore: Update supported ansible-core versions to >=2.15
  README.md
  docs/requirements.txt
  meta/runtime.yml
Labels: approved, release-note, lgtm, size/XS, dco-signoff: yes, major_changes

#106 fix(tests,kubevirt_vm): Fix assertion in verify.yml
  tests/integration/targets/kubevirt_vm/verify.yml
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#108 kubevirt_vm integration tests: changed ssh key type to RSA for FIPS mode
  tests/integration/targets/kubevirt_vm/runme.sh
Labels: release-note-none, approved, lgtm, size/XS, dco-signoff: yes

#101 Change license to Apache 2.0
  LICENSE
  README.md
  hack/e2e-setup.sh
  plugins/doc_fragments/k8s_auth_options.py
  plugins/doc_fragments/k8s_delete_options.py
  plugins/doc_fragments/k8s_state_options.py
  plugins/doc_fragments/kubevirt_auth_options.py
  plugins/inventory/kubevirt.py
  plugins/modules/kubevirt_vm.py
  plugins/modules/kubevirt_vm_info.py
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/plugins/modules/test_kubevirt_vm.py
  tests/unit/plugins/modules/test_kubevirt_vm_info.py
  tests/unit/utils/ansible_module_mock.py
  tests/unit/utils/merge_dicts.py
Labels: approved, release-note, size/XXL, lgtm, dco-signoff: yes

#109 Bump e2e software versions
  Makefile
  hack/e2e-setup.sh
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes

#107 tests: Address comments of #96
  tests/unit/plugins/inventory/test_kubevirt.py
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes

#112 fix(ci): Do not test ansible-core devel with py3.10
  .github/workflows/ci.yml
  .github/workflows/integration.yml
Labels: release-note-none, size/S, dco-signoff: yes

#111 chore: Ensure compatibility with kubernetes.core >=3.1.0,<6.0.0
  requirements.yml
Labels: approved, release-note, lgtm, size/XS, dco-signoff: yes

#97 Inventory unit tests
  tests/unit/plugins/inventory/test_kubevirt.py
  tests/unit/plugins/inventory/test_kubevirt_composable_vars.py
Labels: release-note-none, approved, size/XXL, lgtm, dco-signoff: yes

#113 fix(ci): Do not test ansible-core milestone with py3.10
  .github/workflows/ci.yml
  .github/workflows/integration.yml
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes
